#############################################################################
# Makefile for building: reittiopasqtquick
# Generated by qmake (2.01a) (Qt 4.7.3) on: la 24. maalis 15:14:39 2012
# Project:  reittiopasqtquick.pro
# Template: app
# Command: c:\qtsdk\symbian\sdks\symbian3qt473\bin\qmake.exe -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt473\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf reittiopasqtquick.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbian3qt473\bin\qmake.exe
DEL_FILE          = del 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQT_DECLARATIVE_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/include/QtCore"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/include/QtNetwork"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/include/QtGui"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/include/QtXml"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/include/QtSql"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/include/QtDeclarative"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/include"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/include/QtLocation"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/mkspecs/common/symbian"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/include"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/include/stdapis"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/include/stdapis/sys"  -I"C:/Users/Osku/symbiankoodaus/reittiopas_qtquick/qmlapplicationviewer"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/include/mw"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform/mw"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform/loc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform/mw/loc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/include/platform/mw/loc/sc"  -I"C:/QtMobility"  -I"C:/QtLocation"  -I"C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/include/stdapis/stlportv5"  -I"C:/Users/Osku/symbiankoodaus/reittiopas_qtquick/moc"  -I"C:/Users/Osku/symbiankoodaus/reittiopas_qtquick"  -I"C:/Users/Osku/symbiankoodaus/reittiopas_qtquick/rcc"  -I"C:/Users/Osku/symbiankoodaus/reittiopas_qtquick/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "C:/Users/Osku/symbiankoodaus/reittiopas_qtquick/reittiopasqtquick.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt473\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/Users/Osku/symbiankoodaus/reittiopas_qtquick/reittiopasqtquick.pro
	$(QMAKE) "C:/Users/Osku/symbiankoodaus/reittiopas_qtquick/reittiopasqtquick.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt473\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc: 
	$(QMAKE) "C:/Users/Osku/symbiankoodaus/reittiopas_qtquick/reittiopasqtquick.pro"  -spec ..\..\..\..\QtSDK\Symbian\SDKs\Symbian3Qt473\mkspecs\symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call C:/QtSDK/Symbian/SDKs/Symbian3Qt473/epoc32/release/winscw/udeb/reittiopasqtquick.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis reittiopasqtquick.sis reittiopasqtquick.exe $(QT_RUN_OPTIONS)

reittiopasqtquick_template.pkg: C:/Users/Osku/symbiankoodaus/reittiopas_qtquick/reittiopasqtquick.pro
	$(MAKE) -f $(MAKEFILE) qmake

reittiopasqtquick_installer.pkg: C:/Users/Osku/symbiankoodaus/reittiopas_qtquick/reittiopasqtquick.pro
	$(MAKE) -f $(MAKEFILE) qmake

reittiopasqtquick_stub.pkg: C:/Users/Osku/symbiankoodaus/reittiopas_qtquick/reittiopasqtquick.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: reittiopasqtquick_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	createpackage -g $(QT_SIS_OPTIONS) reittiopasqtquick_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: reittiopasqtquick_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	createpackage -g $(QT_SIS_OPTIONS) -o reittiopasqtquick_template.pkg $(QT_SIS_TARGET)

reittiopasqtquick.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: reittiopasqtquick_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: reittiopasqtquick_installer.pkg
	createpackage $(QT_SIS_OPTIONS) reittiopasqtquick_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: reittiopasqtquick_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: reittiopasqtquick_installer.pkg
	createpackage $(QT_SIS_OPTIONS) -o reittiopasqtquick_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: reittiopasqtquick_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	createpackage -s $(QT_SIS_OPTIONS) reittiopasqtquick_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call reittiopasqtquick.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_qmlapplicationviewer.cpp moc\moc_gps.cpp moc\moc_reittiopas.cpp moc\moc_addressparser.cpp moc\moc_routeparser.cpp moc\moc_legloc.cpp moc\moc_leg.cpp moc\moc_route.cpp moc\moc_dbmanager.cpp moc\moc_s60main.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_qmlapplicationviewer.cpp moc\moc_gps.cpp moc\moc_reittiopas.cpp moc\moc_addressparser.cpp moc\moc_routeparser.cpp moc\moc_legloc.cpp moc\moc_leg.cpp moc\moc_route.cpp moc\moc_dbmanager.cpp moc\moc_s60main.cpp
moc\moc_qmlapplicationviewer.cpp: qmlapplicationviewer\qmlapplicationviewer.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\qmlapplicationviewer\qmlapplicationviewer.h -o c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\moc\moc_qmlapplicationviewer.cpp

moc\moc_gps.cpp: gps.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\gps.h -o c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\moc\moc_gps.cpp

moc\moc_reittiopas.cpp: addressparser.h \
		addresstypewrapper.h \
		routeparser.h \
		route.h \
		leg.h \
		legloc.h \
		dbmanager.h \
		reittiopas.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopas.h -o c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\moc\moc_reittiopas.cpp

moc\moc_addressparser.cpp: addresstypewrapper.h \
		addressparser.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\addressparser.h -o c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\moc\moc_addressparser.cpp

moc\moc_routeparser.cpp: route.h \
		leg.h \
		legloc.h \
		routeparser.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\routeparser.h -o c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\moc\moc_routeparser.cpp

moc\moc_legloc.cpp: legloc.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\legloc.h -o c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\moc\moc_legloc.cpp

moc\moc_leg.cpp: legloc.h \
		leg.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\leg.h -o c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\moc\moc_leg.cpp

moc\moc_route.cpp: leg.h \
		legloc.h \
		route.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\route.h -o c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\moc\moc_route.cpp

moc\moc_dbmanager.cpp: addressparser.h \
		addresstypewrapper.h \
		dbmanager.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\dbmanager.h -o c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\moc\moc_dbmanager.cpp

moc\moc_s60main.cpp: s60main.h
	C:\QtSDK\Symbian\SDKs\Symbian3Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\s60main.h -o c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\moc\moc_s60main.cpp

compiler_rcc_make_all: rcc\qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc\qrc_resources.cpp
rcc\qrc_resources.cpp: resources.qrc \
		arrows.svg \
		launch_icon_reittiopas_black_plain_converted.svg \
		launch_icon_reittiopas.svg \
		img\location_cancel.png \
		img\train.png \
		img\bus.png \
		img\metro.png \
		img\remove_plain.svg \
		img\location.jpg \
		img\walk.jpg \
		img\tram.png \
		img\bus.jpg \
		img\ferry.png \
		img\nightbus.png
	c:\QtSDK\Symbian\SDKs\Symbian3Qt473\bin\rcc.exe -name resources c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\resources.qrc -o c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\rcc\qrc_resources.cpp

compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

dodistclean:
	-@ if EXIST "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick_template.pkg" $(DEL_FILE)  "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick_template.pkg"
	-@ if EXIST "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick_stub.pkg" $(DEL_FILE)  "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick_stub.pkg"
	-@ if EXIST "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick_installer.pkg" $(DEL_FILE)  "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick_installer.pkg"
	-@ if EXIST "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\Makefile" $(DEL_FILE)  "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\Makefile"
	-@ if EXIST "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick_exe.mmp" $(DEL_FILE)  "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick_exe.mmp"
	-@ if EXIST "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick_reg.rss" $(DEL_FILE)  "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick_reg.rss"
	-@ if EXIST "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.rss" $(DEL_FILE)  "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.rss"
	-@ if EXIST "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc" $(DEL_FILE)  "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\reittiopasqtquick.loc"
	-@ if EXIST "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\bld.inf" $(DEL_FILE)  "c:\Users\Osku\symbiankoodaus\reittiopas_qtquick\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


